name: Debug GitHub Actions

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show folder structure
        run: ls -R $GITHUB_WORKSPACE
