      - name: Commit and push updated flight deals
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add flights.json
          git commit -m "Updated flight deals" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/jimenalanda1/Try-2.git main
